[package]
name = "nps"
version = "0.2.0"
description = "Find SEARCH_TERM in available nix packages and sort results by relevance"
authors = ["Ole Mussmann <github+account@ole.mn>"]
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.6"
grep = "0.3.2"
log = "0.4.22"
owo-colors = { version = "4.1.0", features = ["supports-colors"] }
termcolor = "1.4.1"
