name: Code Coverage

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: nps code coverage - latest
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: Set up nix
        run: |
          nix build
          nix flake check

      - name: Setting up channels
        run: |
          nix-channel --add https://nixos.org/channels/nixos-unstable nixos
          nix-channel --update

      - name: Install Rust
        run: rustup update stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: |
          RUST_LOG=TRACE cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 360 --out xml --follow-exec -- --include-ignored

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
