name: Release

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: release nps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release text
        run: |
          TAG=$(grep "## \[" CHANGELOG.md | head -n 2 | tail -n 1 | sed "s/^## \\[\(.*\)\\].*/\1/")
          echo "Tag: '${TAG}'"
          sed -e "/^## \\[${TAG}\\]/,/^## / ! d" CHANGELOG.md | head -n -2 > RELEASE.md
          echo >> RELEASE.md
          sed -e "/^\\[${TAG}\\]: / ! d;s/^\\[${TAG}\\]: \(.*\)/**Full Changelog**: \1/" CHANGELOG.md >> RELEASE.md
          echo "Release text:"
          cat RELEASE.md
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(grep "## \[" CHANGELOG.md | head -n 2 | tail -n 1 | sed "s/^## \\[\(.*\)\\].*/\1/")
          gh release create v"$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} v${TAG#v}" \
              --notes-file="./RELEASE.md" \
              --draft
