name: Cargo Build & Test

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: nps build and test - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: Set up nix
        run: |
          nix build
          nix flake check

      - name: Setting up channels
        run: |
          nix-channel --add https://nixos.org/channels/nixos-unstable nixos
          nix-channel --update

      - name: Test nix search
        run: |
          echo "channels..."
          nix-env -qaP --description
          echo "end test nix search"

      - name: Install Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Run tests
        run: |
          cargo build --verbose
          RUST_LOG=TRACE cargo test --verbose -- --include-ignored --nocapture
